name: tic_tac_toe
description: A super tic-tac-toe game in Dart.
version: 1.0.0
# homepage: https://https://github.com/Lyght/tic-tac-toe

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
